- src/store/modules/swap/eosBancor.ts
- src/store/modules/swap/ethBancor.ts
- src/types/bancor.d.ts
```
interface TxResponse {
txId: string;
blockExplorerLink: string;
}
createPool: (param: CreatePoolParams) => Promise<TxResponse>;
convert: (propose: ProposedConvertTransaction) => Promise<TxResponse>;
updateFee?: (fee: FeeParams) => Promise<TxResponse>;
updateOwner?: (fee: NewOwnerParams) => Promise<TxResponse>;
removeLiquidity: (params: LiquidityParams) => Promise<TxResponse>;
addLiquidity: (params: LiquidityParams) => Promise<TxResponse>;
removeRelay?: (symbolName: string) => Promise<TxResponse>;
```
> WIP: Txlink

- src/api/helpers.ts
- src/components/pool/PoolActionsAddV1.vue
- src/components/pool/PoolActionsAddV2.vue
- src/store/modules/network/eosNetwork.ts
- src/store/modules/swap/eosBancor.ts
- src/store/modules/swap/ethBancor.ts
- src/store/modules/wallet/ethWallet.ts
- src/types/bancor.d.ts
No longer doing maths with Numbers nor storing balances as numbers, using strings instead.
> Numbers to Strings use

- src/components/modals/ModalUnstake.vue
> fix unstake box

- .eslintrc.js
- src/api/eth/contractTypes.ts
- src/api/eth/contractWrappers.ts
- src/api/helpers.ts
- src/api/web3.ts
- src/store/config.ts
- src/store/modules/governance/ethGovernance.ts
- src/store/modules/swap/ethBancor.ts
- src/store/modules/swap/index.ts
This is what I was tinkering with, probably useless to you @H34D might be better off looking at this fresh. 
For whatever reason positions are failing to be fetched or calculated properly. The last thing I did was looking at 
```
console.log("blockNumber");
const currentBlockNumber = await web3.eth.getBlockNumber();
console.log("blockNumberEnd");
```
It seemed to be failing.
> Add a way to have read only providers to retrieve data from (via alchemy) without losing the ability yo transact with a given provider

- src/components/layout/BancorMenu.vue
- src/components/protection/AddProtectionDouble.vue
> Fix broken link for discord

- src/components/data/details/DataDetailsPool.vue
- src/components/data/details/DataDetailsToken.vue
- src/components/protection/AddProtectionSingle.vue
- src/components/vote/proposals/Proposals.vue
This PR fixes multiple smaller issues:
- https://github.com/bancorprotocol/webapp/issues/431
- https://github.com/bancorprotocol/webapp/issues/494
- https://github.com/bancorprotocol/webapp/issues/472
> Multiple smaller fixes

- .github/workflows/build_and_test.yml
- tests/unit/pureHelpers.spec.ts
> Add automatic tests and build upon push

- package.json
- src/components/modals/ModalSelects/ModalTokenSelect.vue
- src/store/modules/swap/ethBancor.ts
auto search for newly added tokens
> load token metadata and put it into search when adding a new token

- src/api/eth/contractTypes.ts
- src/api/eth/ethAbis.ts
- src/api/helpers.ts
- src/api/pureHelpers.ts
- src/components/protection/AddProtectionSingle.vue
- src/store/modules/swap/ethBancor.ts
- src/store/modules/swap/index.ts
- tests/unit/ProgressBar.spec.ts
- tests/unit/TestWorld.spec.ts
- tests/unit/calculatePriceDeviationTooHigh.spec.ts
> Feature price deviation message

- src/assets/_scss/custom/_variables.scss
- src/components/common/RemainingTime.vue
> fix css for remaining time

- src/components/layout/SideBarBottom.vue
> fix css for removing strange figure

- src/components/common/DataTableResponsive.vue
- src/components/vote/proposals/OpenProposals.vue
- src/components/vote/stake/Stake.vue
> Showing vote area on mobile

- src/api/web3.ts
> Add reconnect property on websocketProvider

- src/store/modules/swap/ethBancor.ts
Fixes #585 
Setting resolveImeediately as true at resolveTxOnConfirmation function In the last transaction.
- addProtection
- removeProtection
- protectLiquidity
- addLiquidity
- removeLiquidity
> Transaction confirmation popup - show etherscan link right away #585

- src/components/common/RemainingTime.vue
- src/components/vote/VotePage.vue
- src/components/vote/proposals/LayoutProposals.vue
- src/components/vote/proposals/OpenProposals.vue
- src/components/vote/stake/Stake.vue
- yarn.lock
> Fix css issue on voting page

- src/components/vote/proposals/LayoutProposals.vue
- src/components/vote/proposals/OpenProposals.vue
- tests/unit/ProgressBar.spec.ts
- tests/unit/calculatePriceDeviationTooHigh.spec.ts
- tests/unit/common/LabelContentSplit.spec.ts
- yarn.lock
- Fixed : #683 
https://github.com/bancorprotocol/webapp/pull/677#issuecomment-742390106
https://github.com/bancorprotocol/webapp/pull/677#issuecomment-742454448
> Update css for improving design

- src/components/common/LabelContentSplit.vue
- src/components/swap/SwapAction.vue
> Add tooltip for slippage indication

- src/components/vote/proposals/LayoutProposals.vue
- src/components/vote/proposals/OpenProposals.vue
- src/types/bancor.d.ts
- tests/unit/__mocks__/helpersMock.ts
> Refactor interface field

- src/components/protection/AddProtectionSingle.vue
> Fix incorrect input number when available is zero

- src/components/common/RemainingTime.vue
- src/components/vote/proposals/AddProposal.vue
- src/components/vote/proposals/OpenProposals.vue
- src/store/modules/governance/ethGovernance.ts
> Show tx confirm msg once tx is mined

- jest.config.js
- src/api/pureHelpers.ts
- src/assets/icons.ts
- src/components/layout/Navigation.vue
- src/components/layout/SideBarBottom.vue
- src/components/layout/SideBarLeft.vue
- tests/unit/__mocks__/helpersMock.ts
> improve navigation design

- src/components/layout/SideBarLeft.vue
> Add roundness on sidebar when close

- src/components/layout/SideBarLeft.vue
> Change logo once minimizing menu

- src/components/data/pooltokentables/TablePools.vue
- src/components/swap/SwapAction.vue
> Fix swap too fast and data table layout

- src/api/eth/contractTypes.ts
- src/api/eth/ethAbis.ts
- src/api/observables.ts
- src/api/pureHelpers.ts
- src/store/modules/rewards/index.ts
- src/store/modules/swap/eosBancor.ts
- src/store/modules/swap/ethBancor.ts
- src/store/modules/swap/staticRelays.ts
- src/utils/dayjs.ts
- tests/unit/pureHelpers.spec.ts
> Fetch pool programs from onchain

- src/components/protection/ProtectedSummary.vue
- src/components/rewards/RewardsSummary.vue
- src/store/modules/swap/ethBancor.ts
- src/views/ProtectionHome.vue
> improve zero positions handling

- src/components/common/TokenInputField.vue
- src/components/layout/BancorMenu.vue
- src/components/layout/Navigation.vue
- src/components/layout/SettingsMenu.vue
- src/components/layout/SideBarBottom.vue
- src/components/modals/ModalStake.vue
- src/components/modals/ModalUnstake.vue
- src/components/rewards/RewardsSummary.vue
> dark mode fixes

- src/assets/_scss/custom/_styles.scss
- src/assets/_scss/custom/_variables.scss
- src/components/layout/SubNavigation.vue
> Swap/pool tab hover fix.

- src/components/vote/proposals/AddProposal.vue
> Confirmation pop up to new proposal.

- src/components/common/ActionModalStatus.vue
- src/components/protection/WithdrawProtectionSingle.vue
- src/views/ProtectionHome.vue
> Added notice text after withdraw and scroll to closed pos table.

- src/components/protection/AddProtectionSingle.vue
- src/components/protection/WithdrawProtectionSingle.vue
- src/store/modules/swap/ethBancor.ts
This reverts commit a9ab3e1a753a1ffd3fd1c3731309725b9771bec8.
> Revert "temporary disable price deviation"

- src/api/eth/bancorApi.ts
> update api endpoint

- src/components/layout/SideBar.vue
- src/components/modals/ModalVoteDetails.vue
- src/components/vote/proposals/OpenProposals.vue
- src/i18n/en.ts
> update tooltip text

- src/components/protection/AddProtectionSingle.vue
- src/i18n/en.ts
> Fixed type error in case both tokens are disabled.

- src/components/common/AlertBlock.vue
- src/components/protection/WithdrawProtectionSingle.vue
- src/components/rewards/WithdrawRewards.vue
> Warning messages fixes

- tests/unit/pureHelpers.spec.ts
https://github.com/bancorprotocol/webapp/pull/1006#issuecomment-780220070
> Added a test.

- src/components/protection/AddProtectionSingle.vue
- src/i18n/en.ts
> New message where both reserves are disabled in a pool

- src/store/modules/swap/ethBancor.ts
> Remove liq throwing BigNumber error

- src/components/rewards/RestakeRewards.vue
- src/components/rewards/RewardsSummary.vue
> Disabled pools in restakeRewards

- src/components/protection/WithdrawProtectionSingle.vue
- src/store/modules/rewards/index.ts
- src/store/modules/swap/ethBancor.ts
- src/types/bancor.d.ts
> Refactor fetchRewardsMultiplier

- src/components/protection/AddProtectionSingle.vue
- src/i18n/en.ts
> Disabled messages and visibility changes

- src/components/modals/ModalUnstake.vue
> Change button label to unstake when withdrawing

- src/components/protection/AddProtectionSingle.vue
> Price deviation

- src/components/protection/AddProtectionSingle.vue
- src/components/protection/StakeButtons.vue
- src/components/rewards/RestakeRewards.vue
> one second delay.

- src/api/helpers.ts
added this part to the code:
const walletChecks = [
{ checkName: 'derivationPath' },
{ checkName: 'accounts' },
{ checkName: 'connect' },
{ checkName: 'network' },
{ checkName: 'balance', minimumBalance: '1000000' }
]
> adding support for hardware wallets

- src/api/helpers.ts
Reverts bancorprotocol/webapp#1112
> Revert "adding support for hardware wallets"

- src/components/common/ContentBlock.vue
- src/components/common/MultiInputField.vue
- src/components/data/pooltokentables/PoolTokenTables.vue
- src/components/modals/ModalBase.vue
- src/components/pool/YourLiquidity.vue
> Search box clear

- src/components/layout/BancorMenu.vue
- src/i18n/en.ts
> Menu Reorder

- src/components/data/pooltokentables/TablePools.vue
- src/i18n/en.ts
- src/i18n/he.ts
> Rewards ended

- src/components/common/ContentBlock.vue
- src/components/common/TablePagination.vue
- src/components/data/DataSummary.vue
- src/views/ProtectionHome.vue
> Tables bottom navigation

- src/components/common/AnimationNumber.vue
> Animation number fix

- src/api/helpers.ts
> Support for hardware wallets

- src/components/common/MultiInputField.vue
- src/components/common/SlippageTolerance.vue
- src/components/common/TokenInputField.vue
> Formatter for fields

- src/components/pool/create/CreateV1TokenBlock.vue
> Disabled create pool slider

- src/components/protection/ProtectedTable.vue
- src/i18n/en.ts
- src/i18n/he.ts
Branched from #1364
Solves #1363
> Protected Table tooltip

- src/App.vue
Reverts bancorprotocol/webapp#1390
> Revert "loading false once tokens are available"

- src/store/modules/swap/ethBancor.ts
> APR N/A to 0

- src/components/pool/PoolToken.vue
> Fixed pool token search

- package.json
- src/App.vue
- src/components/pool/ModalPoolAction.vue
- src/main.ts
- yarn.lock
This reverts commit 47749daa617048b38d925c627b7447e672fa8f26.
> Revert "Removed gtag"

- src/components/rewards/WithdrawRewards.vue
- src/i18n/en.ts
> Withdraw text update

- src/components/modals/ModalSelects/ModalDurationSelect.vue
- src/components/swap/SwapLimit.vue
> Limit orders 30 days

- src/gtm/index.ts
- src/i18n/index.ts
> Language in GTM

- src/components/swap/SwapMarket.vue
- src/i18n/en.json
- src/store/modules/swap/ethBancor.ts
> Insufficient liqudity check
